USE [wangh21_IN705Assignment1]
GO

CREATE TABLE Category
(
	CategoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CategoryName NVARCHAR(20) NOT NULL
)
GO

CREATE TABLE Contact
(
	ContactID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ContactName NVARCHAR(100) NOT NULL,
	ContactPhone NVARCHAR(15) NOT NULL,
	ContactFax NVARCHAR(15) NULL,
	ContactMobilePhone NVARCHAR(15) NULL,
	ContactEmail NVARCHAR(255) NULL,
	ContactWWW NVARCHAR(255) NULL,
	ContactPostalAddress NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE Supplier
(
	SupplierID INT PRIMARY KEY NOT NULL,
	SupplierGST INT NOT NULL,
	CONSTRAINT FK_Supplier_Contact
	FOREIGN KEY (SupplierID)
	REFERENCES Contact (ContactID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

CREATE TABLE Customer
(
	CustomerID INT PRIMARY KEY NOT NULL,
	CONSTRAINT FK_Customer_Contact
	FOREIGN KEY (CustomerID)
	REFERENCES Contact (ContactID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
GO

CREATE TABLE Component
(
	ComponentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ComponentName NVARCHAR(100) NOT NULL,
	ComponentDescription NVARCHAR(1000) NOT NULL,
	TradePrice MONEY NOT NULL CHECK (TradePrice >= 0) DEFAULT 0,
	ListPrice MONEY NOT NULL CHECK (ListPrice >= 0) DEFAULT 0,
	TimeToFit DECIMAL CHECK (TimeToFit >= 0) NOT NULL DEFAULT 0,
	CategoryID INT NOT NULL,
	SupplierID INT NOT NULL,
	CONSTRAINT FK_Component_Category
	FOREIGN KEY (CategoryID)
	REFERENCES Category (CategoryID)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	CONSTRAINT FK_Component_Supplier
	FOREIGN KEY (SupplierID)
	REFERENCES Supplier (SupplierID)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
)
GO

CREATE TABLE Quote
(
	QuoteID  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	QuoteDescription NVARCHAR(1000) NOT NULL,
	QuoteDate DATE NOT NULL,
	QuotePrice MONEY NULL,
	QuoteCompiler NVARCHAR(100) NOT NULL,
	CustomerID INT NOT NULL,
	CONSTRAINT FK_Quote_Customer
	FOREIGN KEY (CustomerID)
	REFERENCES Customer (CustomerID)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
)
GO

CREATE TABLE QuoteComponent
(
	ComponentID INT PRIMARY KEY NOT NULL,
	QuoteID  INT NOT NULL,
	Quantity INT NOT NULL DEFAULT 0,
	TradePrice MONEY NOT NULL CHECK (TradePrice >= 0) DEFAULT 0,
	ListPrice MONEY NOT NULL CHECK (ListPrice >= 0) DEFAULT 0,
	TimeToFit DECIMAL CHECK (TimeToFit >= 0) NOT NULL DEFAULT 0,
	CONSTRAINT FK_QuoteComponent_Quote
	FOREIGN KEY (QuoteID)
	REFERENCES Quote (QuoteID)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	CONSTRAINT FK_QuoteComponent_Component
	FOREIGN KEY (ComponentID)
	REFERENCES Component (ComponentID)
	--ON UPDATE CASCADE
	ON DELETE NO ACTION
)
GO

CREATE TABLE AssemblySubcomponent
(
	AssemblyID INT PRIMARY KEY NOT NULL,
	SubcomponentID INT NOT NULL,
	Quantity INT NOT NULL DEFAULT 0,
	CONSTRAINT FK_Subcomponent_Component
	FOREIGN KEY (SubcomponentID)
	REFERENCES Component (ComponentID)
	ON UPDATE CASCADE,
	--ON DELETE NO ACTION,
	CONSTRAINT FK_Assembly_Component
	FOREIGN KEY (AssemblyID)
	REFERENCES Component (ComponentID)
	--ON UPDATE CASCADE
	ON DELETE NO ACTION
)
GO
